### ISSUE TITLE
Feature request: throttle down TCP using flow control in case of slow data consumers

### ISSUE THREAD

**Issue by gicho** [erian747/lwip#1]
I have a proposal for extension of the code, and the API of mqtt. It is intended to support cases where large payloads are received from the broker (e.g. incomming publish events). In this case the final destination in the system, e.g. a storage device, might be too slow to cope with the speed of the TCP link between the broker and the LWIP.
Here is the suspisious point that might need some reworking:
https://github.com/erian747/lwip/blob/4e34851c57c754d2a91aac4b920f094aabd62f5a/src/apps/mqtt/mqtt.c#L874
In the current state, the tcp_recved() will be called just before the callback, and the pbuf will be freed just after the callback. This imposes limitation that the callback has to complete all processing of given data at once. 
In real world, this callback will forward received data segment to another task for processing. This is fine because we have to not block the LWIP context. So we speak about asynchronous operation that just starts in the callback, and will complete later. 
By calling tcp_recved() we do give a green light to the stack to ACK this seq and we allow more data to flow in from broker to our client. But the actual data endpoint still runs the asynchronous processing and did not complete. This leads to ineffective flow control on TCP level and we need to take measures on application level against this - e.g. to not allow big payloads to flow.
In fact we have all required flow control features in the TCP layer - if we could only pospone the call to "tcp_recved()" until the time when application processing completes and responds back?
Another idea might be to support "zero copy" mode - this means to postpone also the "pbuf_free()" call that currently stays right after the callback. This will leave the payload in the pbuf and we can safely consume the data from the application task even if we don't copy.
I did made some trials but there seems to be some complications for the second part - the pbuf_free() - the pbuf pointer "p" is not available in the user incomming callback so it cannot be used later if a new public API routine is called when asynchronous processing is ready. Maybe this could (and need to) be solved with different style of buffer handling - pbuf one seems to be reserved for in-stack uses and is not intended to be accessible from outside?
My goal is be able to throttle the speed of the TCP transfer down automatically based on the internal consumer speed. This is needed in some cases. Addind some new public API routines (1 or 2 - one for tcp_recved() and one for pbuf_free() ) will not break the current use style - the user is allowed to call both of them inside the callback - so he/she will achieve the current behavior.

**Comment by erian747** [comment]
I agree, flow control would be a good idea to implement in MQTT data
reception, and i i think your design proposals sounds reasonable
Unfortunately right now i have not that much time to spare for working with
lwip
I think you should create a task at
https://savannah.nongnu.org/projects/lwip/ ,implement your proposals and
discuss with the active maintainers of lwip



2017-10-27 22:12 GMT+02:00 gicho <notifications@github.com>:

**Comment by gicho** [comment]
Thank you, I will try to implement a test version.
